### ISSUE TITLE
har.json missing

### ISSUE THREAD

**Issue by Temperantius** [RORIdev/moesharp#1]
Good day.

After i get the "Cookie grabbed" message, it says that the "har.json" file could not be found.
Where can i get that .json?

**Comment by alikindsys** [comment]
That's wierd. Since cookie grabbed it's har.json itself. Have you installed the dependencies? (Python 3 and it's modules, java) If not please see the readme file.

**Comment by Temperantius** [comment]
I did that already. I did it again to be sure, I get an "already satisfied" message on each one. I'm running Python 3.7 as well.
Here it was it looks like.
 
![Screenshot_2](https://user-images.githubusercontent.com/58359196/69900911-82420200-138a-11ea-87c8-5f1aa210ca82.png)

**Comment by alikindsys** [comment]
That's wierd. Can you please run the python script alone to see what errors it has? Just use `python grab.py link`

**Comment by RORIdev** [comment]
Oh. Also it seems that it had a timeout connecting to Chrome. Does you have it installed?

**Comment by Temperantius** [comment]
Yes, Chrome is installed. I get the same timeout error whether Chrome runs or not.
I used the line and it says that the browsermob-proxy server process failed to start, and that i should check the server log.

All it says is: " '.' is not recognized as an internal or external command,
operable program or batch file."

**Comment by alikindsys** [comment]
yep. you need java. thats the missing link.

**Comment by Temperantius** [comment]
Java 8 Update 231 is installed though. 64 Bit. 
Did i install it wrong or something? Or perhaps a wrong version?

**Comment by alikindsys** [comment]
I narrowed down the issue. it was on the python script. Windows has reversed slashes instead of normal ones. Now you can get har.json. I'm getting an NRE and need further debugging. An fix for windows is really close.

**Comment by Temperantius** [comment]
Thanks for all your work! You're a lifesaver.

**Comment by alikindsys** [comment]
Thanks for your support! wouldn't had find the issue if it weren't for you.

**Comment by alikindsys** [comment]
WINDOWS FIX : https://github.com/RORIdev/moesharp/releases/tag/wf

**Comment by Temperantius** [comment]
Yeah, this works alright. Thanks a lot!
Wierd thing is, now it works when i use  .\moesharp, but not with  ./moesharp.
Was that what you meant with "reversed slashes"?

![Screenshot_1](https://user-images.githubusercontent.com/58359196/69911221-70fc0280-1429-11ea-9009-c08f52b8b20d.png)

**Comment by Temperantius** [comment]
Sorry i missclicked

**Comment by alikindsys** [comment]
Exactly. that s a thing from windows they used the reversed slash instead of the normal slash like in *nix systems

**Comment by alikindsys** [comment]
Issue is closed, if you have any problems please reopen it.
