### ISSUE TITLE
New problem in new program

### ISSUE THREAD

**Issue by RandomUser779** [RORIdev/moesharp#4]
I tried the program but I have another problem. The episode corresponding to the link I input was captured, but the program seems to hit an error and stopped loading. I tried both versions of moekt.jar files, but the issues were the same. Here is a screenshot of it, what might be the problem?
![Problem](https://user-images.githubusercontent.com/72160539/94946182-52b1d800-050e-11eb-84ac-c807e36fde32.png)

**Comment by alikindsys** [comment]
Oh... Although the episode was detected properly it failed on getting the video object from animetwist. Let me check that anime in specific too see if i also get that same problem. Its very unlikely that animetwist changed their layout, so the xpath should work.

**Comment by alikindsys** [comment]
Bug was replicated. Will check if that happens with any anime.

**Comment by alikindsys** [comment]
Bug was found to happen in any anime. This really is an unfortunate timing window, lel. animetwist changed their website a day after i release the tool, completely invalidating the previous xpaths. Should be a simple fix.

**Comment by alikindsys** [comment]
animetwist is having issues at the moment. Please be pacient as it seems to be an issue with their end and not the tool.
![](https://i.imgur.com/UffVke6.png)

**Comment by alikindsys** [comment]
Newest update fixes the issue with xpaths. Just tested it. That combined with a AT outage made that error.
```
[Bungou Stray Dogs 3] was detected successfully!
Getting episodes for : [Bungou Stray Dogs 3]
Current episode : 1
Current episode : 2
Current episode : 3
Current episode : 4
Current episode : 5
Current episode : 6
Current episode : 7
Current episode : 8
Current episode : 9
Current episode : 10
Current episode : 11
Current episode : 12
Finished getting episodes for Bungou Stray Dogs 3. Count : 12
[1/12] Downloading Bungou Stray Dogs 3 - Episode 1 to [C:\Users\roridev\Development\moesharp\anime\Bungou Stray Dogs 3\1.mp4]
```

Issue closed.

**Comment by alikindsys** [comment]
Thanks for reporting this bug btw

**Comment by RandomUser779** [comment]
Thanks for attending to this issue so promptly. The fix worked fine, but just a minor (I hope it's minor haha) problem left. I posted the new problem as a new issue.
