### ISSUE TITLE
Problem: site's "error video" was downloaded instead

### ISSUE THREAD

**Issue by RandomUser779** [RORIdev/moesharp#5]
Hi, I have tried the tool, everything looked fine. Link and episodes were detected correctly, and the downloads occurred properly. However, the "error video" was downloaded instead of the actual anime. The site seems to be still working on browser, though.
I understand that Twist did some changes to their site code or sth, is this problem associated with it?

Here is the screenshot of the file ran:
![image](https://user-images.githubusercontent.com/72160539/94981637-5113fe80-0566-11eb-827e-483b21e7ebd6.png)

Here is the screenshot of the site's "error video":
![image](https://user-images.githubusercontent.com/72160539/94981652-7a348f00-0566-11eb-899e-45b30f5ebca4.png)

**Comment by alikindsys** [comment]
eeeeeew. animetwist is broken again. i'll add a workaround for that since that issue didn't appear in my testing. Thats the "Snap!" page's video btw. Before i do any changes let me check the link of it.

**Comment by alikindsys** [comment]
In the meantime, can you try deleting one of the files and running it again?

**Comment by RandomUser779** [comment]
I have tried 3 times a few moments ago, and 1 more time now. But the problem still persists. Though, if the problem lies in their site, I think we have to wait for maybe a few hours to try again.

**Comment by alikindsys** [comment]
The wierdest part is that, that issue never really showed up during my testing. weren't for you i wouldn't know. so i'm thankful for that. Already working on a workaround for that.

**Comment by alikindsys** [comment]
Reason found. it affects ~~your anime in specific. which is wierd.~~ animes with numbers on them, my code was dumb.

**Comment by RandomUser779** [comment]
Oh, so animes with multiple seasons would have that problem? That sounds not too big of a bug (I hope), and your code only will get better from these issues!

**Comment by alikindsys** [comment]
> Oh, so animes with multiple seasons would have that problem? That sounds not too big of a bug (I hope), and your code only will get better from these issues!

Any anime that has a number on their name, due to lazy programming wouldn't work. I've made the an rookie of a mistake on that one. That was sad and inexcusable. oh well, time to nuke some old releases and make this one the 1.0 version :)

**Comment by alikindsys** [comment]
the download has the right mp4 header, which means that was just faulty business logic. 
![](https://i.imgur.com/YRngEpB.png)
![](https://i.imgur.com/HPZCaay.png)
That'll soon be the only version you can download so no problems.  
Just make sure to **delete all the previous files** and you'll be fine.

**Comment by alikindsys** [comment]
Aaaaand fixed. Thanks for reporting again.

**Comment by alikindsys** [comment]
[Released. Sorry for the minor inconveniences, lel.](https://github.com/RORIdev/moesharp/releases/tag/kt-1.3)

**Comment by RandomUser779** [comment]
Thanks for your hard work, it is working fine now. Cheers
